version: '3.8'
services:
  app:
    build: .
    ports:
      - "3333:3333"
    container_name: task-api-container
    volumes:
      - .:/usr/src/app
    command: npm run start:dev
    networks:
      - task-network
    environment:
      - NODE_ENV=development

  taskdb:
    image: postgres:latest
    networks:
      - task-network
    container_name: task-db-container
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: task-db
      POSTGRES_PASSWORD: task-db
      POSTGRES_DB: task-db
    ports:
      - '5432:5432'
    restart: unless-stopped
    healthcheck:
      test: [ 'CMD-SHELL', 'pg_isready -U task-db' ]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  task-network:
    driver: bridge
